name: Comment Failure
on:
  workflow_run:
    workflows: [ "Check Files" ]
    types: [ completed ]

permissions:
  pull-requests: write
  actions: read

jobs:
  comment_failure:
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.conclusion == 'failure
    steps:
      - name: Print Event
        run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github.event)}}
